apiVersion: v1
kind: Namespace
metadata:
  name: kiam-example
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Secret
metadata:
  name: kiam-server-tls
  namespace: kiam-example
type: Opaque
data:
  server.pem: ${server_pem}
  server-key.pem: ${server_key_pem}
  ca.pem: ${ca_pem}
---
apiVersion: v1
kind: Secret
metadata:
  name: kiam-agent-tls
  namespace: kiam-example
type: Opaque
data:
  server.pem: ${agent_pem}
  server-key.pem: ${agent_key_pem}
  ca.pem: ${ca_pem}
